### ISSUE TITLE
upgrading from car to tank, then placing down car

### ISSUE THREAD

**Issue by billbo99** [Gerkiz/Spiderissmo#2]
After you upgrade your surface to a tank surface,  you can place down a car and it is still linked to the newly upgrade tank surface.

I see when you upgrade your tank surface to a spiderton you can no longer put down a car or tank,  maybe something similar needs to be done to prevent the case scenario in the first paragraph

**Comment by Gerkiz** [comment]
Please feel free to upload a new issue if this is still the case. Cannot reproduce.
