### ISSUE TITLE
Destroyed Entities break the mod

### ISSUE THREAD

**Issue by kasanryukin** [Gerkiz/Spiderissmo#6]
I was doing some testing because I cannot figure out how to upgrade beyond the car despite having dozens of tanks and spidertrons. I destroyed the Car thinking it would destroy the surface and let me get a new one with a spidertron, but it didn't and placing new cards doesn't link the original car surface.  Essentially, the mod is now bricked.

**Comment by Gerkiz** [comment]
This sounds weird. I'll need to check it out!

Any steps on how to reproduce this? If not, it's going to take a little while until I find the culprit.

**Comment by Gerkiz** [comment]
So the upgrade path seems still correct.
1. Place car, mine it -> "username, the car surface has been saved."
2. Place tank, mine it -> "Your car-surface has been upgraded!"
3. Place spidertron, mine it -> "Your car-surface has been upgraded!"

Placing a car, tank or spidertron while you've already placed a car, tank, spidertron prints the message: "Multiple vehicles are not supported at the moment".

Please free to recreate a new issue on how to reproduce your error that you get.
